"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import { 
  Truck, 
  Shield, 
  Save, 
  CheckCircle, 
  Info, 
  Zap, 
  RefreshCw, 
  Eye, 
  EyeOff, 
  AlertCircle,
  ExternalLink
} from "lucide-react";
import type { ShippingSettings } from "@/types/database";
import { updateShippingSettings } from "@/lib/actions/admin";

export default function ShippingSettingsClient({ initialSettings }: { initialSettings: ShippingSettings | null }) {
  const router = useRouter();

  const [settings, setSettings] = useState<Partial<ShippingSettings>>({
    provider: "shiprocket",
    shiprocket_email: initialSettings?.shiprocket_email || "",
    shiprocket_password: initialSettings?.shiprocket_password || "",
    shiprocket_token: initialSettings?.shiprocket_token || "",
    pickup_location: initialSettings?.pickup_location || "Primary",
    origin_pincode: initialSettings?.origin_pincode || "362220",
    warehouse_name: initialSettings?.warehouse_name || "Keshod Central Logistics Hub",
    default_weight: initialSettings?.default_weight || "1.0",
    is_test_mode: initialSettings?.is_test_mode ?? true,
    is_enabled: initialSettings?.is_enabled ?? true,
  });

  const [showPassword, setShowPassword] = useState(false);
  const [saving, setSaving] = useState(false);
  const [savedSuccess, setSavedSuccess] = useState(false);

  // Connection testing state
  const [testingConnection, setTestingConnection] = useState(false);
  const [testResult, setTestResult] = useState<{ success: boolean; message: string } | null>(null);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    setSaving(true);
    setSavedSuccess(false);

    try {
      await updateShippingSettings(settings);
      localStorage.setItem("sivansh_shipping_settings", JSON.stringify(settings));
      setSavedSuccess(true);
      router.refresh();
      setTimeout(() => setSavedSuccess(false), 4000);
    } catch (err: any) {
      alert("Failed to save shipping settings: " + err.message);
    } finally {
      setSaving(false);
    }
  };

  const handleTestConnection = async () => {
    if (!settings.shiprocket_email && !settings.shiprocket_token) {
      setTestResult({
        success: false,
        message: "Please enter your Shiprocket Email & Password or Bearer Token first."
      });
      return;
    }

    setTestingConnection(true);
    setTestResult(null);

    try {
      const res = await fetch("/api/admin/shipping/test-connection", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email: settings.shiprocket_email,
          password: settings.shiprocket_password,
          token: settings.shiprocket_token,
        }),
      });

      const data = await res.json();
      setTestResult({
        success: data.success,
        message: data.message || (data.success ? "Connection established successfully!" : "Connection failed.")
      });

      // If token was auto-generated by the test endpoint, optionally store it
      if (data.token && !settings.shiprocket_token) {
        setSettings(prev => ({ ...prev, shiprocket_token: data.token }));
      }
    } catch (err: any) {
      setTestResult({
        success: false,
        message: "Connection test error: " + (err.message || "Network timeout")
      });
    } finally {
      setTestingConnection(false);
    }
  };

  const isConfigured = Boolean(
    (settings.shiprocket_email && settings.shiprocket_password) || settings.shiprocket_token
  );

  return (
    <div className="space-y-6 max-w-4xl">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-serif text-white">Logistics & Shiprocket Settings</h1>
          <p className="text-neutral-400 text-sm mt-1">
            Configure Shiprocket API credentials, origin pickup hub, and multi-carrier dispatch settings.
          </p>
        </div>
        <a
          href="https://app.shiprocket.in/api-details"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg border border-white/10 bg-white/[0.03] hover:bg-white/[0.08] text-xs font-mono text-neutral-300 transition-colors w-fit"
        >
          <span>Shiprocket API Portal</span>
          <ExternalLink className="w-3.5 h-3.5 text-[#c5a059]" />
        </a>
      </div>

      {savedSuccess && (
        <div className="p-4 bg-emerald-900/30 border border-emerald-500/50 rounded-lg text-emerald-300 text-sm flex items-center gap-2 animate-fade-in">
          <CheckCircle className="w-4 h-4 shrink-0" />
          <span>Shiprocket configuration successfully updated and synced across all store servers!</span>
        </div>
      )}

      <form onSubmit={handleSave} className="space-y-6">
        {/* Shiprocket Primary Status Card */}
        <div className="bg-[#121212] border border-[#c5a059]/30 rounded-xl p-6 space-y-4 shadow-lg">
          <div className="flex items-center justify-between pb-3 border-b border-white/10">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-lg bg-[#c5a059]/10 border border-[#c5a059]/30 flex items-center justify-center text-[#c5a059]">
                <Truck className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-white font-medium text-base">Shiprocket Multi-Carrier Network</h2>
                <p className="text-neutral-400 text-xs">Direct API Integration (Delhivery, Blue Dart, DTDC, Shadowfax, Xpressbees)</p>
              </div>
            </div>

            <span className={`px-3 py-1 rounded text-xs font-mono font-bold border ${
              isConfigured
                ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/30"
                : "bg-[#c5a059]/10 text-[#c5a059] border-[#c5a059]/30"
            }`}>
              {isConfigured ? "LIVE CONNECTED" : "READY FOR CREDENTIALS"}
            </span>
          </div>

          <div className="p-4 bg-white/[0.02] border border-white/5 rounded-lg text-xs leading-relaxed text-neutral-300 flex items-start gap-2.5">
            <Info className="w-4 h-4 text-[#c5a059] shrink-0 mt-0.5" />
            <div>
              <strong>Intelligent Fallback Architecture:</strong> When credentials are not yet entered, the customer checkout automatically runs in <strong>Simulation Fallback Mode</strong> with realistic rates and estimates from Keshod (362220). Once you input your Shiprocket email and password below, it immediately starts making live requests to your Shiprocket account.
            </div>
          </div>

          {/* Form Fields */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 pt-2">
            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Shiprocket Email (Account or API User) <span className="text-[#c5a059]">*</span>
              </label>
              <input
                type="email"
                placeholder="e.g. your-email@gmail.com"
                value={settings.shiprocket_email || ""}
                onChange={(e) => setSettings({ ...settings, shiprocket_email: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white focus:border-[#c5a059] focus:outline-none"
              />
            </div>

            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Shiprocket Password <span className="text-[#c5a059]">*</span>
              </label>
              <div className="relative">
                <input
                  type={showPassword ? "text" : "password"}
                  placeholder="Enter Shiprocket password"
                  value={settings.shiprocket_password || ""}
                  onChange={(e) => setSettings({ ...settings, shiprocket_password: e.target.value })}
                  className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 pr-10 text-xs text-white focus:border-[#c5a059] focus:outline-none"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute right-2.5 top-1/2 -translate-y-1/2 text-neutral-400 hover:text-white transition-colors"
                >
                  {showPassword ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                </button>
              </div>
            </div>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Pickup Location Nickname <span className="text-[#c5a059]">*</span>
              </label>
              <input
                type="text"
                placeholder="e.g. Primary or Keshod Hub"
                value={settings.pickup_location || "Primary"}
                onChange={(e) => setSettings({ ...settings, pickup_location: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white focus:border-[#c5a059] focus:outline-none font-mono"
              />
              <p className="text-[10px] text-neutral-500 mt-1">
                Must match the exact pickup address name registered in your Shiprocket Settings → Pickup Address.
              </p>
            </div>

            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Shiprocket Bearer Token (Optional Override)
              </label>
              <input
                type="text"
                placeholder="Auto-generated from email/password if left empty"
                value={settings.shiprocket_token || ""}
                onChange={(e) => setSettings({ ...settings, shiprocket_token: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white font-mono focus:border-[#c5a059] focus:outline-none"
              />
              <p className="text-[10px] text-neutral-500 mt-1">
                Optional. If email and password are provided, the system auto-refreshes the token for you.
              </p>
            </div>
          </div>

          {/* Test Connection Button & Result */}
          <div className="pt-2 border-t border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <button
              type="button"
              disabled={testingConnection}
              onClick={handleTestConnection}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg border border-[#c5a059]/40 bg-[#c5a059]/10 hover:bg-[#c5a059]/20 text-[#c5a059] text-xs font-semibold transition-all disabled:opacity-50 cursor-pointer w-fit"
            >
              {testingConnection ? (
                <>
                  <RefreshCw className="w-3.5 h-3.5 animate-spin" />
                  <span>Verifying with Shiprocket API...</span>
                </>
              ) : (
                <>
                  <Zap className="w-3.5 h-3.5" />
                  <span>Test Live Shiprocket Connection</span>
                </>
              )}
            </button>

            {testResult && (
              <div className={`p-2.5 rounded text-xs flex items-center gap-2 ${
                testResult.success 
                  ? "bg-emerald-900/30 text-emerald-300 border border-emerald-500/30" 
                  : "bg-rose-900/30 text-rose-300 border border-rose-500/30"
              }`}>
                {testResult.success ? <CheckCircle className="w-4 h-4 shrink-0" /> : <AlertCircle className="w-4 h-4 shrink-0" />}
                <span>{testResult.message}</span>
              </div>
            )}
          </div>
        </div>

        {/* Origin Warehouse Details */}
        <div className="bg-[#121212] border border-[#c5a059]/30 rounded-xl p-6 space-y-4 shadow-lg">
          <h2 className="text-white font-medium text-base flex items-center gap-2">
            <Shield className="w-4 h-4 text-[#c5a059]" />
            <span>Keshod Origin Warehouse & Dispatch Defaults</span>
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Warehouse Pickup Pincode
              </label>
              <input
                type="text"
                value={settings.origin_pincode || "362220"}
                onChange={(e) => setSettings({ ...settings, origin_pincode: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white font-mono font-bold focus:border-[#c5a059] focus:outline-none"
              />
            </div>

            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Default Package Weight (kg)
              </label>
              <input
                type="text"
                value={settings.default_weight || "1.0"}
                onChange={(e) => setSettings({ ...settings, default_weight: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white font-mono focus:border-[#c5a059] focus:outline-none"
              />
            </div>

            <div>
              <label className="block text-xs uppercase font-mono tracking-wider text-neutral-400 mb-1.5">
                Origin Facility Name
              </label>
              <input
                type="text"
                value={settings.warehouse_name || "Keshod Central Logistics Hub"}
                onChange={(e) => setSettings({ ...settings, warehouse_name: e.target.value })}
                className="w-full bg-[#181818] border border-white/15 rounded px-3.5 py-2 text-xs text-white focus:border-[#c5a059] focus:outline-none"
              />
            </div>
          </div>
        </div>

        {/* Submit Bar */}
        <div className="flex justify-end pt-2">
          <button
            type="submit"
            disabled={saving}
            className="btn btn-gold flex items-center gap-2 px-6 py-2.5 text-xs font-bold uppercase tracking-wider rounded-lg shadow-lg hover:shadow-[#c5a059]/20 transition-all cursor-pointer"
          >
            {saving ? (
              <>
                <RefreshCw className="w-4 h-4 animate-spin" />
                <span>Saving Configuration...</span>
              </>
            ) : (
              <>
                <Save className="w-4 h-4" />
                <span>Save Shiprocket Settings</span>
              </>
            )}
          </button>
        </div>
      </form>
    </div>
  );
}
